---
# SPDX-FileCopyrightText: 2022 Wilfred Nicoll <xyzroller@rollyourown.xyz>
# SPDX-License-Identifier: GPL-3.0-or-later

- name: Provision PostgreSQL container image
  hosts: packer

  vars_files:
    # Control node configuration
    - "{{ playbook_dir }}/../../../ryo-control-node/configuration/configuration.yml"
    # Host configuration
    - "{{ playbook_dir }}/../../../ryo-host/configuration/configuration_{{ host_id }}.yml"
    # Module configuration
    - "{{ playbook_dir }}/../../configuration/configuration.yml"

  roles:
    - role: upgrade-container
    - role: install-iptables
    - role: install-cron
    - role: install-consul
    - role: install-postgres
    - role: set-up-firewall
    - role: set-up-consul
    - role: set-up-postgres
