---
## The generic directory /var/containers/{{ module_id }}
## for LXD container persistent storage must be created
## Further module-specific container directories should be
## added here
## -----------------------------------------------------------

## Directories for module-specific LXD container persistent storage
## -----------------------------------------------------------------

- name: Create a directory to mount in module containers
  file:
    path: "/var/containers/{{ module_id }}"
    state: directory
    mode: '0755'

- name: Create a directory for postgres configuration
  file:
    path: /var/containers/{{ module_id }}/config
    state: directory
    mode: '0755'

- name: Create a directory for postgres data
  file:
    path: /var/containers/{{ module_id }}/data
    state: directory
    mode: '0755'

- name: Create a directory for postgres backup
  file:
    path: /var/containers/{{ module_id }}/backup
    state: directory
    mode: '0755'
