#cloud-config
# SPDX-FileCopyrightText: 2022 Wilfred Nicoll <xyzroller@rollyourown.xyz>
# SPDX-License-Identifier: GPL-3.0-or-later

package_upgrade: false
runcmd:
  # Bootstrap postgresql
  - /usr/local/bin/postgres-bootstrap.sh
  # Deploy backup cronjob
  - /usr/local/bin/deploy-cron.sh