---
# SPDX-FileCopyrightText: 2022 Wilfred Nicoll <xyzroller@rollyourown.xyz>
# SPDX-License-Identifier: GPL-3.0-or-later

# Add signing key
#
- name: Add PostgreSQL signing key
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present

# Add repository
#
- name: Set up PostgreSQL repositories
  apt_repository:
    repo: 'deb http://apt.postgresql.org/pub/repos/apt focal-pgdg main'
    state: present
    update_cache: yes


# Install packages
- name: Install PostgreSQL packages for PostgreSQL version {{ postgres_version }}
  apt:
    name: postgresql-{{ postgres_version }}
    update_cache: yes
    state: present
